/**
 * Builds every generated asset, then renders README.md.
 *
 * Run with no arguments to build everything; pass names to build a subset:
 *   node scripts/build.mjs boot workload
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { BOTH, MONO } from './theme.mjs';
import { ASSETS, loadProfile, loadContributions } from './lib/paths.mjs';
import { bootSvg } from './build-boot.mjs';
import { workloadSvg } from './build-workload.mjs';
import { agentCardSvg } from './build-agents.mjs';
import { renderReadme } from './render-readme.mjs';
import { svgDoc, rect, circle, text } from './lib/svg.mjs';

/** Writes `<name>-dark.svg` and `<name>-light.svg` from a per-theme builder. */
async function emitPair(name, build) {
  for (const theme of BOTH) {
    const svg = build(theme);
    await writeFile(join(ASSETS, `${name}-${theme.name}.svg`), svg, 'utf8');
    console.log(`  ${name}-${theme.name}.svg  ${svg.length.toLocaleString('en-US')} bytes`);
  }
}

/**
 * Stand-in for the snake, which is drawn by Platane/snk in CI and cannot run
 * here. Rendered in-palette so the preview reads as a finished page rather than
 * a missing asset, and labelled so nobody mistakes it for the real thing.
 */
function snakePlaceholderSvg(theme) {
  const W = 880;
  const H = 190;
  const cells = [];

  // A quiet suggestion of the contribution grid behind the label.
  for (let col = 0; col < 52; col++) {
    for (let row = 0; row < 7; row++) {
      const level = (col * 7 + row * 3) % 11;
      cells.push(rect({
        x: 26 + col * 16, y: 40 + row * 16, width: 11, height: 11, rx: 2,
        fill: theme.ramp[level > 4 ? 0 : level], opacity: 0.5,
      }));
    }
  }

  return svgDoc({
    width: W,
    height: H,
    title: 'Contribution snake — placeholder',
    desc: 'Placeholder for the contribution snake, which is generated by Platane/snk in CI.',
    css: `text{font-family:${MONO}}`,
    body: [
      rect({ x: 0.5, y: 0.5, width: W - 1, height: H - 1, rx: 9, fill: theme.bg, stroke: theme.border }),
      ...cells,
      rect({ x: 258, y: 76, width: 364, height: 38, rx: 6, fill: theme.panel, stroke: theme.border }),
      circle({ cx: 280, cy: 95, r: 4, fill: theme.amber }),
      text('snake drawn by Platane/snk in CI', { x: 294, y: 99, 'font-size': 12, fill: theme.dim }),
      text('placeholder — run the runtime workflow to replace this', {
        x: W / 2, y: 158, 'font-size': 10, fill: theme.dim, 'text-anchor': 'middle', opacity: 0.75,
      }),
    ].join(''),
  });
}

const TARGETS = {
  boot: (ctx) => emitPair('boot', (theme) => bootSvg(theme, ctx.profile)),

  workload: (ctx) => emitPair('workload', (theme) => workloadSvg(theme, ctx.profile, ctx.contributions)),

  agents: async (ctx) => {
    for (const [i, agent] of ctx.profile.agents.entries()) {
      await emitPair(`agent-${agent.id}`, (theme) => agentCardSvg(theme, agent, i));
    }
  },

  /**
   * The snake is drawn by Platane/snk in CI, not here -- but its colours come
   * from theme.mjs like everything else, so retheming does not leave one
   * graphic in the old palette. The workflow feeds this file to the action.
   */
  snake: async () => {
    const spec = BOTH.map((theme) => {
      const params = new URLSearchParams({
        color_snake: theme.cyan,
        color_dots: theme.ramp.join(','),
      });
      return `assets/snake-${theme.name}.svg?${params}`;
    }).join('\n');
    await writeFile(join(ASSETS, 'snk-outputs.txt'), `${spec}\n`, 'utf8');
    console.log(spec.split('\n').map((l) => `  ${l}`).join('\n'));

    // Placeholders so the local preview has no broken image where the snake
    // goes. The workflow runs snk *after* this step, which overwrites them.
    await emitPair('snake', snakePlaceholderSvg);
    console.log('  snake-*.svg  placeholder (snk overwrites these in CI)');
  },

  readme: async () => {
    const md = await renderReadme();
    console.log(`  README.md  ${md.length.toLocaleString('en-US')} bytes, ${md.split('\n').length} lines`);
  },
};

const requested = process.argv.slice(2);
const names = requested.length ? requested : Object.keys(TARGETS);
const unknown = names.filter((n) => !TARGETS[n]);

if (unknown.length) {
  console.error(`unknown target(s): ${unknown.join(', ')}`);
  console.error(`available: ${Object.keys(TARGETS).join(', ')}`);
  process.exit(1);
}

await mkdir(ASSETS, { recursive: true });
const ctx = { profile: await loadProfile(), contributions: await loadContributions() };

if (ctx.contributions.fromSample) {
  console.log('note: using data/contributions.sample.json (no live fetch present)\n');
}

for (const name of names) {
  console.log(`build ${name}`);
  await TARGETS[name](ctx);
}
